### ISSUE TITLE
The ban time is constantly set to 0

### ISSUE THREAD

**Issue by Rob-bb** [pincioc/fail2ban_mikrotik#1]
With this action: 

action = mtk[list=fail2ban, time='7d 01:00:00']

ban time is set to 0 seconds.  As a work around I have changed the mtk,conf to have this line with hardcoded time.

actionban = `/etc/fail2ban/script/fail2ban_mikrotik.py -m 192.168.88.1 -s 8728 -u ******* -p ******** -a ban -i <ip> -l <list> -d "7d 01:00:00"`

And this works.

**Comment by pincioc** [comment]
I have change arg name from time to dtime

Update the code and try to put in jail rules dtime argument

mtk[list=addresslist, dtime=7d]

I'm waiting for your feedback
